# permissions for end users to edit gpuaddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpuaddon-editor-role
rules:
- apiGroups:
  - nvidia.addons.rh-ecosystem-edge.io
  resources:
  - gpuaddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nvidia.addons.rh-ecosystem-edge.io
  resources:
  - gpuaddons/status
  verbs:
  - get
