# permissions for end users to view gpuaddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpuaddon-viewer-role
rules:
- apiGroups:
  - nvidia.addons.rh-ecosystem-edge.io
  resources:
  - gpuaddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvidia.addons.rh-ecosystem-edge.io
  resources:
  - gpuaddons/status
  verbs:
  - get
